name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'conanfile.py'
      - 'version.txt'
      - '.conan/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - os: windows
            runs_on: windows-latest
            configure_preset: conan-default
          - os: linux
            runs_on: ubuntu-latest
            configure_preset: conan-release

    steps:
    - uses: actions/checkout@v4

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Configure and build
      shell: bash
      run: |
        conan install . -pr .conan/profile -s build_type=Release --build=missing
        cmake --preset ${{ matrix.configure_preset }}
        cmake --build --preset conan-release --config Release

  test:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - os: windows
            runs_on: windows-latest
            configure_preset: conan-default
          - os: linux
            runs_on: ubuntu-latest
            configure_preset: conan-debug

    steps:
    - uses: actions/checkout@v4

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Build and run tests
      working-directory: tests
      shell: bash
      run: |
        conan install . -pr ../.conan/profile -s build_type=Debug --build=missing
        cmake --preset ${{ matrix.configure_preset }}
        cmake --build --preset conan-debug
        ctest --preset conan-debug --output-on-failure
